name: Sync Docs Folder

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # runs daily

jobs:
  sync_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Pull the docs folder from the other repository
        run: |
          git clone --depth 1 https://github.com/simonhansul/docs.git temp_repo
          rm -rf docs/
          mv temp_repo/docs/ docs/
          rm -rf temp_repo/
          git config --global user.email "simonhansul@gmail.com"
          git config --global user.name "Simon Hansul"
          git add docs/
          git commit -m "Sync docs folder from other-repository"
          git push
